[pytest]
log_cli = true
log_cli_level = INFO
testpaths = tests
python_files = test_*.py
addopts = 
    -v 
    --alluredir=allure-results
markers = 
    smoke:smoke tests
    regression:regression tests